#!c:\users\daniele\desktop\lgk-hub\lgk_venv\scripts\python.exe
# Copyright 2014-2017, Damian Johnson and The Tor Project
# See LICENSE for licensing information

import stem.interpreter

if __name__ == '__main__':
  stem.interpreter.main()
